trigger:
- master

resources:
  repositories:
  - repository: repo_saker_windows
    type: github
    name: 'sakerbuild/saker.windows'
    endpoint: Sipkab
  - repository: repo_saker_apple
    type: github
    name: 'sakerbuild/saker.apple'
    endpoint: Sipkab
  - repository: repo_saker_android
    type: github
    name: 'sakerbuild/saker.android'
    endpoint: Sipkab
    
jobs:
- job:
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
    path: s/ruby-hunter
  - checkout: repo_saker_windows
    path: s/saker.windows
  - checkout: repo_saker_apple
    path: s/saker.apple
    condition: eq( variables['Agent.OS'], 'Darwin' )
  - checkout: repo_saker_android
    path: s/saker.android
    
  - script: curl -L https://api.nest.saker.build/bundle/download/saker.build-v$(curl -s https://mirror.nest.saker.build/badges/saker.build/latest.txt) -o saker.build.jar
    displayName: 'Download saker.build'
    condition: or( eq( variables['Agent.OS'], 'Linux' ), eq( variables['Agent.OS'], 'Darwin' ) )
  - script: powershell $ProgressPreference='silentlyContinue';Invoke-WebRequest "https://api.nest.saker.build/bundle/download/saker.build-v$((Invoke-WebRequest "https://mirror.nest.saker.build/badges/saker.build/latest.txt" -UseBasicParsing).Content)" -OutFile saker.build.jar
    displayName: 'Download saker.build'
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - script: java -jar ../saker.build.jar -bd build -trace pwd://build/build_install.trace install
    displayName: 'Install saker.windows'
    workingDirectory: saker.windows
  - script: java -jar ../saker.build.jar -bd build -trace pwd://build/build_install.trace install
    displayName: 'Install saker.android'
    workingDirectory: saker.android
  - script: java -jar ../saker.build.jar -bd build -trace pwd://build/build_install.trace install
    displayName: 'Install saker.apple'
    workingDirectory: saker.apple
    condition: eq( variables['Agent.OS'], 'Darwin' )
  
  - script: java -jar ../saker.build.jar -bd build -trace pwd://build/build_install.trace install
    displayName: 'Install sipka.rubyhunter'
    workingDirectory: ruby-hunter
    
  - script: java -jar ../saker.build.jar -bd build -trace pwd://build/build_compile_win32.trace install
    displayName: 'Compile win32 sipka.rubyhunter'
    workingDirectory: ruby-hunter
    condition: eq( variables['Agent.OS'], 'Windows_NT' )